### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'cfg/yolov8.yaml'

### ISSUE THREAD

**Issue by luke110** [hustvl/SparseTrack#18]
当我执行对MOT17的train时，执行CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --num-gpus 4  --config-file mot17_train_config.py 报错FileNotFoundError: [Errno 2] No such file or directory: 'cfg/yolov8.yaml'

[11/26 18:57:29 detectron2]: Full config saved to ./yolov8_mix17/config.yaml
Traceback (most recent call last):
  File "/HOME/scw6492/run/luke/yolov8/train.py", line 181, in <module>
    launch(
  File "/data/run01/scw6492/luke/yolov8/detectron2/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/HOME/scw6492/.conda/envs/sparse/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/HOME/scw6492/.conda/envs/sparse/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/HOME/scw6492/.conda/envs/sparse/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data/run01/scw6492/luke/yolov8/detectron2/detectron2/engine/launch.py", line 123, in _distributed_worker
    main_func(*args)
  File "/HOME/scw6492/run/luke/yolov8/train.py", line 176, in main
    do_train(args, cfg)
  File "/HOME/scw6492/run/luke/yolov8/train.py", line 92, in do_train
    model = instantiate(cfg.model)
  File "/data/run01/scw6492/luke/yolov8/detectron2/detectron2/config/instantiate.py", line 83, in instantiate
    return cls(**cfg)
  File "/HOME/scw6492/run/luke/yolov8/models/yolo.py", line 20, in __init__
    self.yaml = cfg if isinstance(cfg, dict) else yaml_model_load(cfg)  # cfg dict
  File "/data/run01/scw6492/luke/yolov8/utils/model_utils.py", line 253, in yaml_model_load
    d = yaml_load(f'cfg/{unified_path}')  # model dict
  File "/data/run01/scw6492/luke/yolov8/utils/model_utils.py", line 221, in yaml_load
    with open(file, errors='ignore', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'cfg/yolov8.yaml'

**Comment by Xavier-Lin** [comment]
Have you renamed the folder name 'SparseTrack' to 'yolov8'? 

After clone the repo from 'v8' branch, you should change the folder name 'SparseTrack' with 'yolov8'.

**Comment by luke110** [comment]
> Have you renamed the folder name 'SparseTrack' to 'yolov8'?
> 
> After clone the repo from 'v8' branch, you should change the folder name 'SparseTrack' with 'yolov8'.

okey,very thanks.
